version: '3.8'

services:
  nopcommerce_web:
    build: .
    container_name: pekin_nopcommerce
    restart: always
    ports:
      - "127.0.0.1:8086:80"
    depends_on:
      - nopcommerce_db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ConnectionString=Host=nopcommerce_db;Database=nopcommerce_db;Username=nopuser;Password=${DB_PASSWORD}
      - ConnectionStrings__DataProvider=postgresql
    volumes:
      - ./Presentation/Nop.Web/Plugins:/app/Plugins
      - ./Presentation/Nop.Web/App_Data:/app/App_Data

  nopcommerce_db:
    image: postgres:15-alpine
    container_name: pekin_db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: nopuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: nopcommerce_db
    volumes:
      - pekin_db_data:/var/lib/postgresql/data

volumes:
  pekin_db_data:
