using System;
using Nop.Core.Configuration;

namespace Nop.Plugin.Payments.Iyzipay;

/// <summary>
/// Represents settings of Iyzipay payment plugin
/// </summary>
public class IyzipayPaymentSettings : ISettings
{
    /// <summary>
    /// Gets or sets API key
    /// </summary>
    public string ApiKey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets secret key
    /// </summary>
    public string SecretKey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets base URL
    /// </summary>
    public string BaseUrl { get; set; } = "https://sandbox-api.iyzipay.com";

    /// <summary>
    /// Gets or sets a value indicating whether to use sandbox environment
    /// </summary>
    public bool UseSandbox { get; set; } = true;

    /// <summary>
    /// Gets or sets webhook URL (read-only, generated by system)
    /// </summary>
    public string WebhookUrl { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets order status after payment
    /// </summary>
    public int OrderStatusAfterPayment { get; set; } = 20; // Processing

    /// <summary>
    /// Gets or sets payment form language
    /// </summary>
    public string PaymentFormLanguage { get; set; } = "tr"; // tr, en, auto


    /// <summary>
    /// Gets or sets a value indicating whether protected shop view is enabled
    /// </summary>
    public bool EnableProtectedShopView { get; set; } = false;

    /// <summary>
    /// Gets or sets protected shop view position (left or right)
    /// </summary>
    public string ProtectedShopViewPosition { get; set; } = "left";

    /// <summary>
    /// Gets or sets payment form working mode
    /// </summary>
    public string PaymentFormMode { get; set; } = "iframe"; // iframe, redirect, popup

    /// <summary>
    /// Gets or sets payment option title
    /// </summary>
    public string PaymentOptionTitle { get; set; } = "Kredi/Banka Kartı ile Öde";

    /// <summary>
    /// Gets or sets a value indicating whether to "additional fee" is specified as percentage. true - percentage, false - fixed value.
    /// </summary>
    public bool AdditionalFeePercentage { get; set; }

    /// <summary>
    /// Gets or sets an additional fee
    /// </summary>
    public decimal AdditionalFee { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether to pass info about purchased items to Iyzipay
    /// </summary>
    public bool PassProductNamesAndTotals { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to send invoice info to Iyzipay
    /// </summary>
    public bool SendInvoiceInfo { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to enable 3D secure
    /// </summary>
    public bool Enable3DSecure { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to enable installment options
    /// </summary>
    public bool EnableInstallmentOptions { get; set; } = true;

    /// <summary>
    /// Gets or sets maximum installment count
    /// </summary>
    public int MaxInstallmentCount { get; set; } = 12;
}
