export const MODULE_PAGES = [
  {
    slug: "bagis-kampanyasi",
    metaTitle: "Dernek Bağış Kampanyası Yazılımı | Pekin Teknoloji",
    metaDesc: "Dernekler ve vakıflar için online bağış kampanyası yönetim sistemi. Hedef sayacı, QR kod ve güvenli ödeme altyapısıyla hızlıca bağış toplayın.",
    badge: "Bağış Modülü",
    icon: "💰",
    accentColor: "#16a34a",
    heroTitle: "Online Bağış Kampanyası Yönetimi",
    heroDesc: "Dernekler ve vakıflar için tasarlanmış profesyonel bağış kampanyası altyapısı. Hedef tutar, süre ve içerik belirleyin; bağışçılarınıza güvenli ödeme sayfası sunun.",
    plan: "Başlangıç",
    stats: [
      { num: "Anında", label: "kampanya yayınlayın" },
      { num: "%100", label: "güvenli ödeme" },
      { num: "Sıfır", label: "komisyon kesintisi" },
    ],
    benefits: [
      { icon: "🎯", title: "Hedef Takibi", desc: "Gerçek zamanlı bağış sayacı ve ilerleme çubuğuyla bağışçılarınızı motive edin." },
      { icon: "📲", title: "QR Kod Desteği", desc: "Her kampanya için otomatik QR kod üretin; broşür, afiş ve sosyal medyada paylaşın." },
      { icon: "🔒", title: "3D Secure Ödeme", desc: "Güvenli ödeme altyapısıyla her bağış 3D Secure koruması altında işlenir." },
    ],
    features: [
      "Kampanya sayfası tek panel üzerinden dakikalar içinde oluşturulur",
      "Hedef tutar, bitiş tarihi ve bağış aralıkları serbestçe belirlenir",
      "Aynı anda birden fazla aktif kampanya yönetilebilir",
      "Bağışçı listesi ve bağış geçmişi admin panelinden takip edilir",
      "Kampanyaya özel paylaşım bağlantısı ve sosyal medya önizleme görseli",
      "Bağış yapıldığında anında bağışçıya teşekkür e-postası gönderilir",
    ],
    howItWorks: [
      { step: "01", title: "Kampanyayı Oluşturun", desc: "Panele girin, kampanya adı, açıklama, hedef tutar ve bitiş tarihini doldurun." },
      { step: "02", title: "Sayfayı Yayınlayın", desc: "Tek tıkla yayına alın. Otomatik bağlantı ve QR kod anında oluşturulur." },
      { step: "03", title: "Bağışlar Toplanır", desc: "Bağışçılar güvenli ödeme sayfasından kredi kartı veya havale ile bağış yapar." },
      { step: "04", title: "Anlık Bildirim Alın", desc: "Her bağış için panelde bildirim, bağışçıya otomatik makbuz gönderilir." },
    ],
    seoContent: [
      "Dernek ve vakıflar için online bağış toplama artık karmaşık bir süreç değil. Pekin Teknoloji bağış kampanyası modülüyle teknik bilgi gerektirmeksizin profesyonel kampanya sayfaları oluşturabilirsiniz. Güvenli ödeme altyapısı, bağışçılarınızın kredi kartı bilgilerini 3D Secure korumasıyla işler.",
      "Geleneksel yöntemlerin aksine online bağış kampanyası yazılımımız, bağışlarınızı gerçek zamanlı izlemenizi sağlar. Kaç kişinin bağış yaptığını, toplam tutarı ve hedefe ne kadar kaldığını dakika dakika görebilirsiniz. Bu şeffaflık hem kurum içi raporlama hem de bağışçı güveni açısından kritik öneme sahiptir.",
      "Çoklu kampanya desteği sayesinde kurban kampanyası ile giysi yardımı kampanyasını aynı anda yönetebilirsiniz. Her kampanyanın kendine ait kısa bağlantısı ve QR kodu olur; bu linkleri sosyal medyada, WhatsApp gruplarında veya basılı materyallerinizde kolayca paylaşabilirsiniz.",
    ],
    faq: [
      { q: "Kaç kampanya aynı anda aktif olabilir?", a: "Seçtiğiniz paket kapsamında sınırsız aktif kampanya oluşturabilirsiniz. Kampanya sayısında üst sınır yoktur." },
      { q: "Bağışçıların ödeme yaptığı sayfa güvenli mi?", a: "Evet. Tüm ödemeler güvenli ödeme altyapısı üzerinden 3D Secure ile işlenir. Kart bilgileri sizin sunucularınızda tutulmaz, ödeme hizmet sağlayıcısında şifreli olarak saklanır." },
      { q: "Kampanya bitince bağışlar otomatik duruyor mu?", a: "Bitiş tarihi belirlenen kampanyalar otomatik olarak kapanır. İstediğiniz zaman manuel olarak da kapatabilir veya süreyi uzatabilirsiniz." },
      { q: "Bağışlar banka hesabıma ne zaman geçer?", a: "Ödeme sağlayıcısına bağlı olarak genellikle 1-2 iş günü içinde hesabınıza yansır. Detaylı vade tablosu için ödeme sağlayıcısı anlaşma şartlarına bakınız." },
    ],
    relatedSlugs: ["duzenli-bagis", "dijital-makbuz", "raporlama"],
  },
  {
    slug: "duzenli-bagis",
    metaTitle: "Düzenli Bağış Otomasyonu Dernek & Vakıf | Pekin Teknoloji",
    metaDesc: "Aylık otomatik bağış talimatı sistemi. Kesintisiz gelir akışı için bağışçılarınızdan düzenli bağış alın. Dernek ve vakıflar için SaaS çözümü.",
    badge: "Gelir Otomasyonu",
    icon: "🔁",
    accentColor: "#2563eb",
    heroTitle: "Düzenli Bağış ile Kesintisiz Gelir Akışı",
    heroDesc: "Bağışçılarınız bir kez talimat versin, her ay otomatik olarak bağış yapılsın. Siz onları hatırlatmadan, onlar sizi unutmadan. Dernek gelirlerinizi öngörülebilir kılın.",
    plan: "Başlangıç",
    stats: [
      { num: "Öngörülebilir", label: "gelir akışı" },
      { num: "Sıfır", label: "manuel takip" },
      { num: "Otomatik", label: "kart tahsilatı" },
    ],
    benefits: [
      { icon: "📆", title: "Aylık Otomatik Tahsilat", desc: "Bağışçı talimatı kurduktan sonra her ay belirtilen tarihte kartından otomatik ödeme alınır." },
      { icon: "📊", title: "Gelir Tahmini", desc: "Aktif düzenli bağışçı sayısı ve ortalama taahhüt tutarından aylık beklenen geliri anlık görün." },
      { icon: "🔔", title: "Başarısız Tahsilat Yönetimi", desc: "Kart başarısız olursa bağışçıya otomatik bildirim gider, yeniden deneme zamanlaması siz belirlersiniz." },
    ],
    features: [
      "Bağışçı kayıt sırasında düzenli bağış seçeneğini aktif edebilir",
      "Aylık, 3 aylık veya yıllık periyot seçenekleri sunulur",
      "Bağışçı istediği zaman panelinden talimatı iptal edebilir",
      "Pasif düzenli bağışçılar için otomatik yeniden aktivasyon hatırlatması",
      "Her periyot sonunda otomatik makbuz ve özet rapor gönderilir",
      "Düzenli bağışçılara özel teşekkür e-posta şablonları",
    ],
    howItWorks: [
      { step: "01", title: "Bağışçı Talimat Kurar", desc: "Bağış sayfasında tutarı ve periyodu seçer, kartını kaydeder." },
      { step: "02", title: "Sistem Onaylar", desc: "İlk bağış anında tahsil edilir, talimat kaydedilir." },
      { step: "03", title: "Otomatik Tahsilat", desc: "Belirlenen tarihte kart otomatik olarak tahsil edilir." },
      { step: "04", title: "Bildirim Gönderilir", desc: "Bağışçıya makbuz, size panel bildirimi anında ulaşır." },
    ],
    seoContent: [
      "Düzenli bağış programları, bağışçının her ay karar vermek zorunda kalmadığı bir yapı kurar. Bir kez taahhüt verir, sistem gerisini halleder. Bu sayede dernek geliri tahmin edilebilir hale gelir ve planlama kolaylaşır.",
      "Pekin Teknoloji düzenli bağış modülü, PCI DSS uyumlu güvenli ödeme altyapısını kullanarak kart bilgilerini güvenle saklar. Tahsilat başarısız olduğunda sistem otomatik olarak yeniden dener ve bağışçıya kart güncelleme bildirimi gönderir.",
      "Küçük dernek ve vakıflar için düzenli bağış en kritik finansal araçtır. Proje harcamalarını planlarken kaç kişinin bağışçı olduğunu değil, her ay ne kadar gelir geleceğini bilmek — işte bu operasyonel güç sağlar.",
    ],
    faq: [
      { q: "Bağışçı talimatı iptal edebilir mi?", a: "Evet. Bağışçı dilediği zaman üye panelinden veya e-posta ile talimatını iptal edebilir. İptal anında bir sonraki tahsilat durur." },
      { q: "Kart başarısız olursa ne olur?", a: "Sistem önce 3 gün, sonra 7 gün arayla iki kez daha dener. Her deneme sonrası bağışçıya bilgilendirme mesajı gönderilir. Üç denemede de başarısız olursa talimat askıya alınır ve sizin panelinize düşer." },
      { q: "Minimum düzenli bağış tutarı nedir?", a: "Platform tarafında minimum tutar bulunmaz. Ödeme sağlayıcısı koşullarına bağlı olarak genellikle 10 TL ve üzeri işlemler sorunsuz çalışır." },
      { q: "Düzenli bağışçı sayısını nereden görüyorum?", a: "Admin panelinin Düzenli Bağışçılar sekmesinde aktif talimat sayısı, toplam aylık taahhüt tutarı ve geçmiş tahsilat başarı oranını görebilirsiniz." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "dijital-makbuz", "whatsapp-bildirimleri"],
  },
  {
    slug: "dijital-makbuz",
    metaTitle: "Otomatik Dijital Bağış Makbuzu Sistemi | Pekin Teknoloji",
    metaDesc: "Her bağış sonrası otomatik PDF makbuz oluşturun ve e-posta ile WhatsApp'tan gönderin. Dernek ve vakıflar için yasal uyumlu dijital makbuz sistemi.",
    badge: "Makbuz Otomasyonu",
    icon: "📄",
    accentColor: "#7c3aed",
    heroTitle: "Otomatik Dijital Bağış Makbuzu",
    heroDesc: "Her bağış gerçekleştiğinde saniyeler içinde profesyonel PDF makbuz oluşturulsun, bağışçıya e-posta ve WhatsApp ile otomatik iletilsin. Makbuz için tek satır kod yazmanıza gerek yok.",
    plan: "Başlangıç",
    stats: [
      { num: "Saniyeler", label: "içinde makbuz" },
      { num: "Otomatik", label: "e-posta + WhatsApp" },
      { num: "PDF", label: "yasal uyumlu format" },
    ],
    benefits: [
      { icon: "📑", title: "Profesyonel PDF Şablonu", desc: "Kurumunuzun logosu ve bilgileriyle özelleştirilmiş, yasal gerekliliklere uygun PDF makbuz." },
      { icon: "⚡", title: "Anında İletim", desc: "Bağış onaylandığı an makbuz bağışçının e-postasına ve WhatsApp numarasına düşer, bekleme yok." },
      { icon: "🗄️", title: "Arşiv & Arama", desc: "Tüm makbuzlar admin panelinde tarih, bağışçı adı ve kampanyaya göre filtrelenerek aranabilir." },
    ],
    features: [
      "Makbuz şablonu kurumsal logo ve renk temasıyla özelleştirilir",
      "Her makbuzda benzersiz seri numarası otomatik atanır",
      "Bağış tutarı, tarihi, kampanya adı ve bağışçı bilgisi makbuzda yer alır",
      "PDF, PNG veya HTML formatında makbuz oluşturma desteği",
      "Toplu makbuz indirme (belirli tarih aralığı için ZIP)",
      "Yanlış makbuz durumunda tek tıkla iptal ve yeniden gönderme",
    ],
    howItWorks: [
      { step: "01", title: "Bağış Onaylanır", desc: "Ödeme sağlayıcısından başarı bildirimi alınır." },
      { step: "02", title: "Makbuz Oluşturulur", desc: "Sistem şablondan otomatik PDF üretir, seri numarası atar." },
      { step: "03", title: "İletim Başlar", desc: "E-posta ve WhatsApp kanalından bağışçıya gönderilir." },
      { step: "04", title: "Arşive Eklenir", desc: "Makbuz admin panelinde kalıcı olarak saklanır, istendiğinde tekrar gönderilebilir." },
    ],
    seoContent: [
      "Dernek ve vakıflar için makbuz düzenleme hem yasal bir yükümlülük hem de bağışçı güvenini pekiştiren önemli bir adımdır. Pekin Teknoloji dijital makbuz modülü, her bağış işleminin ardından saniyeler içinde PDF makbuz oluşturur ve bağışçıya iletir.",
      "Geleneksel yöntemle makbuz kesmek zaman alan ve hata riski taşıyan bir süreçtir. Elden yazılan veya Word üzerinden oluşturulan makbuzlar hem seri numarası tutarsızlıklarına hem de gönderim gecikmelerine yol açar. Otomatik makbuz sistemi bu riski ortadan kaldırır.",
      "Yıl sonunda vergi beyannamesi hazırlayan bağışçılarınız makbuzlarına üye panelinden erişebilir. Müşteri hizmetleri yükünüzü azaltan bu özellik, bağışçı memnuniyetini doğrudan artırır.",
    ],
    faq: [
      { q: "Makbuz şablonunu nasıl özelleştiriyorum?", a: "Panel > Ayarlar > Makbuz Şablonu bölümünden kurumunuzun logosunu, renklerini ve adres bilgilerini girerek şablonu özelleştirebilirsiniz." },
      { q: "Bağışçı makbuzunu kaybederse ne olur?", a: "Bağışçı üye paneline girerek bağış geçmişinden makbuzunu PDF olarak indirebilir. İsterse admin tarafından da makbuz yeniden gönderilebilir." },
      { q: "Makbuzlar yasal olarak geçerli mi?", a: "Makbuz şablonu 2860 sayılı Yardım Toplama Kanunu kapsamındaki temel unsurları içerecek şekilde tasarlanmıştır. Kurumunuzun mali müşaviriyle şablonu gözden geçirmenizi öneririz." },
      { q: "Toplu makbuz gönderimi yapabilir miyim?", a: "Belirli bir tarihe kadar makbuz gönderilmemiş bağışlar için toplu gönderim fonksiyonu mevcuttur. Admin panelinden tarih aralığı seçip Toplu Gönder diyebilirsiniz." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "whatsapp-bildirimleri", "raporlama"],
  },
  {
    slug: "etkinlik-yonetimi",
    metaTitle: "Dernek Etkinlik Yönetim Sistemi | Online Kayıt | Pekin Teknoloji",
    metaDesc: "STK ve dernekler için online etkinlik yönetimi. Katılımcı kaydı, kontenjan takibi ve otomatik hatırlatma mesajlarıyla etkinliklerinizi kolaylıkla yönetin.",
    badge: "Etkinlik Modülü",
    icon: "📅",
    accentColor: "#d97706",
    heroTitle: "Dernek Etkinlik Yönetimi ve Online Kayıt",
    heroDesc: "Seminer, kermes, gala veya gönüllü toplantısı fark etmez — etkinlik sayfanızı dakikalar içinde yayına alın. Katılımcı kayıtlarını, kontenjanı ve hatırlatmaları otomatik yönetin.",
    plan: "Dernek Paneli",
    stats: [
      { num: "Sıfır", label: "manuel kayıt takibi" },
      { num: "Otomatik", label: "katılımcı hatırlatması" },
      { num: "Gerçek zamanlı", label: "kontenjan takibi" },
    ],
    benefits: [
      { icon: "📋", title: "Online Kayıt Formu", desc: "Her etkinlik için özel kayıt formu. İsim, e-posta, telefon ve ek sorular eklenebilir." },
      { icon: "🎟️", title: "Kontenjan Yönetimi", desc: "Etkinlik dolduğunda kayıtlar otomatik kapanır, bekleme listesi oluşturulabilir." },
      { icon: "📩", title: "Otomatik Hatırlatma", desc: "Etkinlik öncesinde 3 gün ve 1 gün önceden otomatik e-posta hatırlatması gönderilir." },
    ],
    features: [
      "Ücretsiz veya ücretli etkinlik seçeneği; ücretli etkinliklerde güvenli online ödeme",
      "Katılımcı listesi Excel ve PDF olarak dışa aktarılabilir",
      "QR kod ile etkinlik girişinde katılımcı doğrulama",
      "Birden fazla oturum veya gün içeren etkinlik desteği",
      "Etkinlik iptalinde otomatik bildirim ve ücret iadesi akışı",
      "Geçmiş etkinlik arşivi ve katılım istatistikleri",
    ],
    howItWorks: [
      { step: "01", title: "Etkinliği Oluşturun", desc: "Başlık, tarih, yer, kontenjan ve kayıt formunu doldurun." },
      { step: "02", title: "Katılımcılar Kaydolur", desc: "Paylaştığınız linke tıklar, formu doldurur ve ücretliyse öder." },
      { step: "03", title: "Otomatik Onay", desc: "Kayıt onay e-postası ve takvim davetiyesi anında gönderilir." },
      { step: "04", title: "Etkinlik Günü", desc: "QR kod ile giriş doğrulama, katılım listesi cep telefonunuzdan takip." },
    ],
    seoContent: [
      "STK ve dernek etkinlikleri telefon veya kağıt listesiyle yönetildiğinde ciddi zaman kaybı ve hata riski doğar. Pekin Teknoloji etkinlik yönetim modülü, kayıt sürecini tamamen dijitalleştirerek hem organizatörlerin hem katılımcıların deneyimini iyileştirir.",
      "Ücretli etkinlikler için güvenli online ödeme altyapısı devrededir. Katılımcılar kredi kartıyla ödeyebilir, kurum anında tahsilat kaydını görür. Kontenjan dolduğunda yeni kayıtlar otomatik olarak bekleme listesine eklenir.",
      "Etkinlik sonrasında katılımcı istatistikleri raporlanır. Bu veriler gelecek etkinliklerin planlanmasında ve bağışçı ilişkileri yönetiminde değerli içgörüler sunar.",
    ],
    faq: [
      { q: "Ücretsiz etkinlikler için de sistemi kullanabilir miyim?", a: "Evet. Ücretsiz etkinliklerde ödeme adımı otomatik olarak atlanır. Yalnızca kayıt formu ve onay e-postası akışı çalışır." },
      { q: "Katılımcı listesini nasıl dışa aktarırım?", a: "Etkinlik detay sayfasında Dışa Aktar butonuyla katılımcı listesini Excel veya PDF formatında indirebilirsiniz." },
      { q: "Kontenjan dolunca ne olur?", a: "Kayıt formu otomatik olarak Bekleme Listesi moduna geçer. Bekleme listesindeki kişiler kayıt açıldığında sırasıyla davet edilir." },
      { q: "Katılımcılara takvim daveti gönderebilir miyim?", a: "Evet. Kayıt onayı e-postasına otomatik olarak Google Takvim ve Outlook uyumlu .ics dosyası eklenir." },
    ],
    relatedSlugs: ["gonullu-koordinasyonu", "whatsapp-bildirimleri", "bagis-kampanyasi"],
  },
  {
    slug: "gonullu-koordinasyonu",
    metaTitle: "Gönüllü Yönetim Sistemi STK & Dernek | Pekin Teknoloji",
    metaDesc: "Dernekler ve STK'lar için gönüllü yönetim yazılımı. Online başvuru, görev atama, vardiya planlama ve gönüllü iletişimini tek platformdan yönetin.",
    badge: "Gönüllü Modülü",
    icon: "👥",
    accentColor: "#0891b2",
    heroTitle: "Gönüllü Yönetim Sistemi",
    heroDesc: "Gönüllü başvurularını toplayın, görev atayın, vardiyaları planlayın. Onlarca gönüllüyü WhatsApp grupları ve e-postalar yerine tek bir sistemden koordine edin.",
    plan: "Dernek Paneli",
    stats: [
      { num: "Tek panel", label: "tüm gönüllü yönetimi" },
      { num: "Otomatik", label: "başvuru akışı" },
      { num: "Kolay", label: "vardiya planlama" },
    ],
    benefits: [
      { icon: "📝", title: "Online Başvuru Formu", desc: "Sitenizde yayınlanan başvuru formuyla gönüllü adayları doğrudan sisteme kayıt olur." },
      { icon: "📌", title: "Görev & Vardiya Atama", desc: "Gönüllülere görevler atayın, takvim üzerinden vardiyaları planlayın, onaylarını alın." },
      { icon: "💬", title: "Merkezi İletişim", desc: "Toplu e-posta ve WhatsApp bildirimleriyle tüm gönüllülere tek mesajla ulaşın." },
    ],
    features: [
      "Gönüllü profili: ilgi alanları, yetkinlikler, müsaitlik takvimi",
      "Görev kategorileri ve etiket sistemi (saha, ofis, online)",
      "Gönüllü saatleri takibi ve yıllık katkı raporu",
      "Başvuru durumu yönetimi (bekleniyor / onaylandı / reddedildi)",
      "Gönüllülere özel sayfa: görevler, belgeler, duyurular",
      "Gönüllü çıkış anketi ve memnuniyet ölçümü",
    ],
    howItWorks: [
      { step: "01", title: "Başvuru Formu Yayınlanır", desc: "Sitenizde gönüllü olmak isteyen adaylar formu doldurup başvurur." },
      { step: "02", title: "Koordinatör İnceler", desc: "Admin panelinde başvuruyu onaylar, reddeder veya bekletir." },
      { step: "03", title: "Görev Atanır", desc: "Onaylanan gönüllüye görev ve vardiya atanır, bildirim gönderilir." },
      { step: "04", title: "Katkı Takip Edilir", desc: "Saat ve görev sayısı otomatik birikir; yıl sonu katkı sertifikası üretilir." },
    ],
    seoContent: [
      "Gönüllü koordinasyonu, derneklerin en zaman alan operasyonel yüklerinden biridir. WhatsApp gruplarında kayıp mesajlar ve Excel tablolarında güncel olmayan listeler yerine merkezi bir gönüllü yönetim sistemi kullanmak hem koordinatörlerin iş yükünü azaltır hem de gönüllü memnuniyetini artırır.",
      "Pekin Teknoloji gönüllü modülü, adayların online başvurudan görev tamamlamaya kadar tüm yolculuğunu sistematik biçimde yönetir. Gönüllülerin ilgi alanları ve müsaitlik takvimleri sisteme girdikten sonra doğru kişiyi doğru göreve atamak dakikalar alır.",
      "Büyük etkinliklerde onlarca gönüllüyü koordine etmek zorunda kalan dernekler için vardiya planlama özelliği özellikle değerlidir. Her gönüllü hangi tarihte, hangi lokasyonda, ne görev yapacağını panelinden görebilir ve onaylayabilir.",
    ],
    faq: [
      { q: "Gönüllüler sisteme nasıl giriş yapıyor?", a: "Onaylanan gönüllülere otomatik olarak üyelik daveti gönderilir. Gönüllü kendi şifresini oluşturup gönüllü paneliyle görevlerini takip eder." },
      { q: "Gönüllü saatleri yasal olarak geçerli belge sayılır mı?", a: "Sistemden alınan katkı raporu, gönüllüye imzalı sertifika olarak verilebilir. Yasal geçerlilik kurumunuzun statüsüne bağlıdır; hukuk danışmanınızla teyit edin." },
      { q: "Farklı şehirlerdeki gönüllüleri yönetebilir miyim?", a: "Evet. Gönüllü profillerinde şehir ve bölge bilgisi tutulur. Görev atamaları lokasyona göre filtrelenerek yapılabilir." },
      { q: "Gönüllü başvurusu için özel sorular ekleyebilir miyim?", a: "Evet. Başvuru formuna metin, çoktan seçmeli veya dosya yükleme türünde özel alanlar eklenebilir." },
    ],
    relatedSlugs: ["etkinlik-yonetimi", "whatsapp-bildirimleri", "raporlama"],
  },
  {
    slug: "whatsapp-bildirimleri",
    metaTitle: "Dernek WhatsApp Bildirim Sistemi | Bağış Onayı & Makbuz",
    metaDesc: "Bağış yapıldığında anında WhatsApp ile bildirim ve makbuz gönderin. Dernekler için otomatik WhatsApp mesaj sistemi, Meta Business API entegrasyonu.",
    badge: "Bildirim Modülü",
    icon: "📱",
    accentColor: "#16a34a",
    heroTitle: "Otomatik WhatsApp Bildirimleri",
    heroDesc: "Bağış onayı, makbuz, kampanya güncellemesi ve etkinlik hatırlatması — hepsi otomatik olarak WhatsApp üzerinden gönderilsin. Bağışçılarınız her zaman bilgilendirilmiş olsun.",
    plan: "Tüm Planlar",
    stats: [
      { num: "%98", label: "WhatsApp açılma oranı" },
      { num: "Saniyeler", label: "içinde iletim" },
      { num: "Otomatik", label: "tüm tetikleyiciler" },
    ],
    benefits: [
      { icon: "✅", title: "Bağış Onay Mesajı", desc: "Her bağış sonrası bağışçıya tutar, tarih ve kampanya bilgisiyle kişiselleştirilmiş mesaj." },
      { icon: "📎", title: "Makbuz WhatsApp ile", desc: "PDF makbuz WhatsApp üzerinden iletilir; e-postayı kontrol etmeyen bağışçılar için kritik kanal." },
      { icon: "📣", title: "Kampanya Güncellemeleri", desc: "Hedefin yüzde ellisine ve yüzde yüzüne ulaşıldığında bağışçılara otomatik güncelleme mesajı." },
    ],
    features: [
      "Meta Business API entegrasyonu ile onaylı WhatsApp şablonları kullanılır",
      "Bağış onayı, makbuz, etkinlik hatırlatması ve düzenli bağış bildirimi şablonları hazır",
      "Özel mesaj şablonları oluşturulabilir (Meta onayı gerektirir)",
      "Mesaj iletim durumu admin panelinde görünür",
      "Başarısız gönderiler otomatik e-posta kanalına yönlendirilir",
      "Bağışçı dilerse WhatsApp bildirimlerinden çıkış yapabilir",
    ],
    howItWorks: [
      { step: "01", title: "Tetikleyici Gerçekleşir", desc: "Bağış onayı, etkinlik kaydı gibi bir eylem sistemi tetikler." },
      { step: "02", title: "Şablon Seçilir", desc: "Tetikleyiciye karşılık gelen onaylı WhatsApp şablonu seçilir." },
      { step: "03", title: "Mesaj Gönderilir", desc: "Kişiselleştirilmiş mesaj anında bağışçının WhatsApp numarasına iletilir." },
      { step: "04", title: "Durum Kaydedilir", desc: "Gönderim durumu ve okunma bilgisi panelde arşivlenir." },
    ],
    seoContent: [
      "E-posta açılma oranları yüzde yirmi ile otuz civarında seyrederken WhatsApp mesajlarının yüzde doksansekiz oranında okunduğu bilinmektedir. Bu fark, bağışçı iletişiminde WhatsApp uygulamasını vazgeçilmez bir kanal haline getirmektedir.",
      "Özellikle makbuz iletiminde WhatsApp kanalının önemi büyüktür. Bağışçıların bir kısmı e-posta kutusunu düzenli kontrol etmez; ancak WhatsApp her zaman açıktır. Makbuzun hem e-posta hem WhatsApp kanalından gönderilmesi, iletim başarı oranını önemli ölçüde artırır.",
      "Kampanya hedefine ulaşıldığında bağışçılara gönderilen hedefe ulaştık mesajı, gelecekteki kampanyalarda yeniden bağış yapma motivasyonunu artıran güçlü bir ilişki kurma aracıdır.",
    ],
    faq: [
      { q: "WhatsApp bildirimleri için ek ücret var mı?", a: "Modül aylık abonelik kapsamındadır. Meta, kişi başına belirli bir ücretsiz konuşma kotası tanır; bu kotanın üzerindeki mesajlar Meta tarafından ücretlendirilir." },
      { q: "Kendi telefon numaramı mı kullanıyorum?", a: "Evet. Kendi kayıtlı işletme telefon numaranızı Meta Business Manager'a ekleyerek sisteme bağlıyoruz. Bağışçılar mesajı sizin numaranızdan alır." },
      { q: "Şablon mesajlar özelleştirilebilir mi?", a: "Hazır şablonlar dışında özel şablonlar oluşturulabilir. Ancak her şablon Meta onayından geçmesi gerekir (genellikle 24-48 saat)." },
      { q: "Bağışçı bildirimi istemiyorsa ne olur?", a: "Bağışçı profil sayfasından veya mesaj içindeki opt-out bağlantısından WhatsApp bildirimlerini devre dışı bırakabilir." },
    ],
    relatedSlugs: ["dijital-makbuz", "bagis-kampanyasi", "duzenli-bagis"],
  },
  {
    slug: "raporlama",
    metaTitle: "Dernek Bağış Raporlama & Şeffaf Mali Rapor | Pekin Teknoloji",
    metaDesc: "Dernek ve vakıflar için şeffaf bağış raporlama sistemi. Kampanya performansı, harcama takibi ve kamuoyuna açık rapor sayfası. STK mali yönetim yazılımı.",
    badge: "Raporlama Modülü",
    icon: "📊",
    accentColor: "#0891b2",
    heroTitle: "Şeffaf Bağış Raporlama Sistemi",
    heroDesc: "Toplanan bağışlar nereye gitti? Kampanyalar ne kadar başarılı oldu? Tüm soruların cevabı tek panelde. Bağışçılarınıza şeffaf olun, güveninizi güçlendirin.",
    plan: "Tüm Planlar",
    stats: [
      { num: "Gerçek zamanlı", label: "bağış verileri" },
      { num: "Otomatik", label: "aylık özet rapor" },
      { num: "Kamuya açık", label: "şeffaflık sayfası" },
    ],
    benefits: [
      { icon: "📈", title: "Kampanya Analitikleri", desc: "Hangi kampanya ne kadar topladı, en fazla bağış hangi kanaldan geldi, ortalama bağış tutarı nedir." },
      { icon: "💸", title: "Harcama Takibi", desc: "Toplanan bağışların harcama kalemlerini panele girin; bağışçılara nereye harcandığını gösterin." },
      { icon: "🌐", title: "Kamuya Açık Rapor", desc: "Sitenizde yayınlanan şeffaflık sayfasıyla bağışçılar ve kamuoyu bağış kullanımını görebilir." },
    ],
    features: [
      "Günlük, haftalık, aylık ve yıllık bağış özeti grafikleri",
      "Bağışçı demografileri: yeni ve tekrar eden, şehir dağılımı",
      "Kampanya karşılaştırma raporu (birden fazla kampanyayı yan yana)",
      "CSV ve PDF formatında rapor dışa aktarma",
      "Otomatik aylık e-posta özet raporu yöneticilere gönderilir",
      "Kamuya açık şeffaflık sayfası (isteğe bağlı yayınlama)",
    ],
    howItWorks: [
      { step: "01", title: "Veriler Otomatik Toplanır", desc: "Her bağış, iptal ve iade raporlama sistemine anında kaydedilir." },
      { step: "02", title: "Panelde Görselleştirilir", desc: "Grafikler ve tablolar üzerinden dilediğiniz zaman dilimi için analiz yapın." },
      { step: "03", title: "Rapor Paylaşın", desc: "PDF veya link olarak yönetim kuruluna veya bağışçılara gönderin." },
      { step: "04", title: "Şeffaflık Sayfası", desc: "Bağış kullanımını kamuya açık sayfada yayınlayarak güven inşa edin." },
    ],
    seoContent: [
      "Türkiye'de sivil toplum kuruluşlarına yönelik güven sorunlarının temelinde şeffaflık eksikliği yatar. Bağışçılar paralarının nereye gittiğini merak eder; bu soruya net ve erişilebilir bir cevap vermek hem mevcut bağışçıları elde tutmak hem de yenilerini çekmek için kritiktir.",
      "Pekin Teknoloji raporlama modülü, kampanya bazında toplanan tutarları ve harcama kalemlerini gerçek zamanlı izlemenizi sağlar. İsteğe bağlı olarak yayınlanan kamuya açık şeffaflık sayfası, herhangi bir bağışçının sitenizi ziyaret ederek bağış kullanımını görmesine olanak tanır.",
      "Yönetim kurulu raporlaması için aylık otomatik PDF özetleri e-posta ile gönderilir. Toplantı öncesinde manuel rapor hazırlamak zorunda kalmaz, sisteminizden alınan rapora güvenebilirsiniz.",
    ],
    faq: [
      { q: "Şeffaflık sayfasını yayınlamak zorunlu mu?", a: "Hayır. Kamuya açık şeffaflık sayfası tamamen isteğe bağlıdır. İstemeyen kurumlar bu özelliği pasife alabilir, yalnızca iç raporlama için sistemi kullanabilir." },
      { q: "Harcama verilerini kim giriyor?", a: "Harcama kalemleri admin panelindeki Harcamalar bölümünden yetkili kullanıcılar tarafından manuel olarak girilir. Fatura veya fiş yüklemesi de yapılabilir." },
      { q: "Raporları yönetim kuruluyla nasıl paylaşırım?", a: "İstediğiniz tarih aralığı için PDF rapor oluşturup doğrudan e-posta olarak gönderebilir ya da şifreli bir link üretip iletebilirsiniz." },
      { q: "Geçmiş verilere de erişebilir miyim?", a: "Sisteme geçiş yaptığınız tarihten itibaren tüm veriler saklanır. Önceki dönem verilerinizi CSV olarak içe aktarma seçeneği de sunulmaktadır." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "dijital-makbuz", "duzenli-bagis"],
  },
  {
    slug: "coklu-dil",
    metaTitle: "Dernek Çok Dilli Bağış Sitesi | Yurt Dışı Bağış | Pekin Teknoloji",
    metaDesc: "Türkçe, İngilizce ve daha fazla dilde bağış kampanyası yayınlayın. Yurt dışındaki bağışçılara TL, dolar ve euro ile bağış imkânı sunun. STK çok dilli platform.",
    badge: "Çoklu Dil & Kur",
    icon: "🌐",
    accentColor: "#7c3aed",
    heroTitle: "Çok Dilli Bağış Sitesi ve Yurt Dışı Bağış",
    heroDesc: "Diaspora ve yurt dışı bağışçılarınıza ulaşın. Kampanya sayfalarınızı Türkçe, İngilizce ve diğer dillerde yayınlayın; TL, dolar veya euro ile bağış alın.",
    plan: "Dernek Paneli",
    stats: [
      { num: "10+", label: "desteklenen dil" },
      { num: "TL $ €", label: "para birimi desteği" },
      { num: "Otomatik", label: "dil tespiti" },
    ],
    benefits: [
      { icon: "🌍", title: "Otomatik Dil Tespiti", desc: "Ziyaretçinin tarayıcı diline göre site otomatik doğru dile geçer." },
      { icon: "💱", title: "Çoklu Para Birimi", desc: "Yurt dışı bağışçılar kendi para birimiyle bağış yapabilir; kur dönüşümü otomatik hesaplanır." },
      { icon: "✍️", title: "Kolay Çeviri Yönetimi", desc: "Admin panelinden her dil için metin düzenlemesi yapılır, teknik bilgi gerekmez." },
    ],
    features: [
      "Türkçe, İngilizce, Arapça, Almanca ve daha fazlası desteklenir",
      "Her dil için bağımsız kampanya başlığı ve açıklaması girilebilir",
      "Ödeme sayfası da seçilen dilde gösterilir",
      "Döviz kuru otomatik güncellenir (günlük merkez bankası kuru)",
      "Makbuzlar bağışçının seçtiği dilde oluşturulur",
      "Arama motorlarında her dil için ayrı bağlantı yapısı (hreflang desteği)",
    ],
    howItWorks: [
      { step: "01", title: "Dilleri Aktif Edin", desc: "Panelden desteklemek istediğiniz dilleri seçin ve para birimlerini etkinleştirin." },
      { step: "02", title: "Çevirileri Girin", desc: "Her kampanya ve sayfa için dilediğiniz dilde içerik yazın ya da çeviri servisinden alın." },
      { step: "03", title: "Ziyaretçi Dilini Seçer", desc: "Bağışçı dil simgesine tıklar ya da tarayıcı dili otomatik algılanır." },
      { step: "04", title: "Bağış Kendi Dövizinde", desc: "Seçilen para biriminde bağış yapılır, hesabınıza dönüştürülerek yansır." },
    ],
    seoContent: [
      "Türkiye'deki derneklerin önemli bir kısmı yurt dışında yaşayan diaspora topluluklarından bağış almaktadır. Bu bağışçılara sadece Türkçe içerik sunan tek dilli bir site ciddi bir engel oluşturur. Çok dilli platform bu engeli ortadan kaldırarak erişilebilirliği genişletir.",
      "Almanya, Hollanda, ABD ve Avustralya'daki Türk diasporası için İngilizce veya Almanca kampanya sayfaları, bağış oranlarını doğrudan etkiler. Bunun yanı sıra bağışçının kendi para birimiyle ödeme yapabilmesi dönüşüm oranını artıran kritik bir kolaylıktır.",
      "SEO açısından hreflang etiketi desteği, her dilin kendi bağlantısında arama motorlarına sunulmasını sağlar. Bu yapı, farklı ülke ve dillerde organik arama sıralaması elde etmek için vazgeçilmezdir.",
    ],
    faq: [
      { q: "Yurt dışından gelen bağışlar nasıl tahsil ediliyor?", a: "Uluslararası kart kabulü için güvenli ödeme entegrasyonu kullanılır. Tahsilat seçtiğiniz para biriminde hesabınıza geçer." },
      { q: "Arapça gibi sağdan sola yazılan diller destekleniyor mu?", a: "Evet. RTL diller için arayüz otomatik olarak yansıtılır." },
      { q: "Döviz kuru nasıl belirleniyor?", a: "Günlük TCMB kuru temel alınarak otomatik güncellenir. İsterseniz kendiniz sabit kur da belirleyebilirsiniz." },
      { q: "Makbuzlar hangi dilde gönderiliyor?", a: "Bağışçının bağış sırasında seçtiği dilde makbuz oluşturulur ve gönderilir." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "raporlama", "sosyal-paylasim"],
  },
  {
    slug: "sosyal-paylasim",
    metaTitle: "Bağış Kampanyası Sosyal Medya Paylaşımı | Online Fundraising",
    metaDesc: "Dernek bağış kampanyalarınızı sosyal medyada yayın. Instagram, Facebook ve WhatsApp için otomatik önizleme görseli. Online fundraising için STK araçları.",
    badge: "Sosyal Paylaşım",
    icon: "🔗",
    accentColor: "#db2777",
    heroTitle: "Kampanyaları Sosyal Medyada Yayın",
    heroDesc: "Bağış kampanyanızı Instagram, Facebook, Twitter ve WhatsApp üzerinden bir tıkla paylaşın. Otomatik önizleme görseli ve özel hashtag desteğiyle kampanyanızın viral yayılmasını destekleyin.",
    plan: "Tüm Planlar",
    stats: [
      { num: "1 tık", label: "ile tüm platformlarda" },
      { num: "Otomatik", label: "önizleme görseli" },
      { num: "Daha fazla", label: "organik erişim" },
    ],
    benefits: [
      { icon: "🖼️", title: "Otomatik OG Görseli", desc: "Kampanya paylaşıldığında sosyal medyada kampanya adı ve tutarını gösteren çarpıcı önizleme kartı." },
      { icon: "📲", title: "Tek Tık Paylaşım", desc: "Kampanya sayfasındaki paylaş butonu Instagram, Facebook, Twitter ve WhatsApp'a yönlendirir." },
      { icon: "🏷️", title: "Hashtag Öneri", desc: "Kampanyaya özel hashtag önerisi; takipçilerinizi harekete geçirmek için hazır içerik şablonları." },
    ],
    features: [
      "Her kampanya için otomatik Open Graph meta etiketi oluşturulur",
      "Bağışçılar bağış yaptıktan sonra ben de bağış yaptım paylaşım kartı üretebilir",
      "Kampanya güncelleme mesajlarını sosyal medyaya zamanlamayla planlayın",
      "Hangi sosyal kanaldan kaç tıklama geldiğini UTM parametreleriyle izleyin",
      "Kısa bağlantı desteği paylaşımı kolaylaştırır",
      "Bağışçıların referans kodu ile gelen bağışları takip edin",
    ],
    howItWorks: [
      { step: "01", title: "Kampanya Oluşturun", desc: "Kampanya başlığı, görseli ve açıklaması otomatik OG kartına dönüşür." },
      { step: "02", title: "Paylaşım Linkleri", desc: "Kampanya sayfasındaki paylaş butonları tüm platformlara hazır link üretir." },
      { step: "03", title: "Bağışçı Yayılımı", desc: "Bağış yapanlar ben de bağış yaptım kartıyla ağlarına duyurur." },
      { step: "04", title: "Trafik İzlenir", desc: "Hangi paylaşımdan kaç ziyaret ve bağış geldiği panelde görünür." },
    ],
    seoContent: [
      "Online fundraising'in en güçlü kanalı sosyal medya ağları üzerinden yayılan eş referansıdır. Bir bağışçının ben de bağış yaptım paylaşımı, kurumunuzun organik erişiminin çok ötesinde bir kitleye ulaşabilir. Bu viral mekanizmayı sistematik hale getirmek, kampanya başarısını doğrudan etkiler.",
      "Pekin Teknoloji sosyal paylaşım modülü, her kampanya için otomatik Open Graph meta etiketleri oluşturur. Bu sayede kampanya bağlantısı Facebook veya WhatsApp'ta paylaşıldığında kampanya adı, görseli ve kısa açıklamasını içeren çarpıcı bir önizleme kartı otomatik olarak görünür.",
      "UTM parametreli izleme linkleri sayesinde hangi sosyal medya kanalının en fazla bağışçı getirdiğini analiz edebilir ve gelecek kampanyalarda içerik planlamanızı buna göre yapabilirsiniz.",
    ],
    faq: [
      { q: "Instagram'da da paylaşım yapılabiliyor mu?", a: "Instagram dış link paylaşımını kısıtlar. Instagram Hikayeler için QR kod veya bio bağlantısı yönlendirmesiyle kampanya trafiği sağlanır. Hazır hikaye şablonları modül kapsamında sunulur." },
      { q: "Ben de bağış yaptım kartı nasıl çalışıyor?", a: "Bağış başarıyla tamamlandığında bağışçıya kampanya adı ve anonim bağış miktarı içeren paylaşım kartı gösterilir. Bağışçı dilerse sosyal medyasında paylaşabilir." },
      { q: "Referans kodu ile gelen bağışları nasıl izliyorum?", a: "Her bağışçı veya gönüllüye özel referans kodu verilebilir. Bu kod üzerinden yapılan bağışlar admin panelinde ayrıca raporlanır." },
      { q: "Kampanya güncellemelerini otomatik paylaşabilir miyim?", a: "Doğrudan otomatik sosyal medya yayını yapılamaz. Ancak hedef belirli bir orana ulaşıldığında hazır paylaşım metni ve görseli oluşturulur, sosyal medya yöneticiniz kolayca paylaşabilir." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "whatsapp-bildirimleri", "raporlama"],
  },
  {
    slug: "bagisci-yonetimi",
    metaTitle: "Bağışçı Yönetim Sistemi Dernek & Vakıf | Pekin Teknoloji",
    metaDesc: "Dernek ve vakıflar için bağışçı CRM yazılımı. Bağışçı profili, geçmiş takibi, segmentasyon ve otomatik iletişimle bağışçı sadakatini artırın.",
    badge: "Bağışçı CRM",
    icon: "👤",
    accentColor: "#7c3aed",
    heroTitle: "Bağışçı Yönetimi ve CRM",
    heroDesc: "Her bağışçınızın kim olduğunu, ne zaman ve ne kadar bağış yaptığını bilin. Segmentlere ayırın, doğru mesajı doğru kişiye gönderin. Bağışçı sadakatini sistematik hale getirin.",
    plan: "Dernek Paneli",
    stats: [
      { num: "%60+", label: "daha yüksek tekrar bağış" },
      { num: "360°", label: "bağışçı profili" },
      { num: "Otomatik", label: "teşekkür iletişimi" },
    ],
    benefits: [
      { icon: "📋", title: "Eksiksiz Profil", desc: "Her bağışçının iletişim bilgileri, bağış geçmişi, kampanya katılımları ve notları tek sayfada." },
      { icon: "🎯", title: "Segmentasyon", desc: "Yeni bağışçı, düzenli bağışçı, pasif bağışçı gibi gruplara ayırarak hedefli iletişim kampanyaları oluşturun." },
      { icon: "💌", title: "Otomatik Teşekkür", desc: "Bağış sonrası kişiselleştirilmiş teşekkür e-postası ve SMS otomatik gönderilir; ilişki sıcaklığı korunur." },
    ],
    features: [
      "Her bağışçı için ad, soyad, e-posta, telefon ve adres kaydı tutulur",
      "Bağışçı bazında toplam bağış tutarı ve kampanya geçmişi görüntülenir",
      "Pasif bağışçılar otomatik olarak tespit edilir, yeniden aktivasyon mesajı gönderilir",
      "Bağışçılar etiket ve segment sistemiyle gruplandırılabilir",
      "Toplu e-posta ve SMS kampanyaları segmentlere gönderilir",
      "KVKK uyumlu veri saklama ve bağışçı veri silme talebi yönetimi",
    ],
    howItWorks: [
      { step: "01", title: "Bağışçı Kaydedilir", desc: "Bağış yapan her kişi otomatik olarak sisteme eklenir, profili oluşturulur." },
      { step: "02", title: "Geçmiş Takip Edilir", desc: "Tüm bağış ve kampanya etkileşimleri profilde birikir, zaman çizelgesiyle görülür." },
      { step: "03", title: "Segmentlere Ayrılır", desc: "Bağış sıklığına, tutara veya ilgi alanına göre bağışçılar otomatik gruplara atanır." },
      { step: "04", title: "İletişim Kurulur", desc: "Segmente uygun teşekkür, hatırlatma veya kampanya mesajı toplu olarak iletilir." },
    ],
    seoContent: [
      "Dernek ve vakıflar için bağışçı kazanmak kadar elde tutmak da kritiktir. Araştırmalar, mevcut bir bağışçıyı tekrar bağışa yönlendirmenin yeni bir bağışçı kazanmaktan beş kat daha az maliyetli olduğunu göstermektedir. Bağışçı yönetim sistemi bu süreci otomatikleştirir.",
      "Pekin Teknoloji bağışçı CRM modülü her bağışçının 360 derece profilini tutar. Kim ne zaman bağış yapmış, hangi kampanyalara katılmış, son bağışı ne kadardı gibi sorulara anında yanıt bulunur. Bu veriler hem kişiselleştirilmiş iletişim hem de strateji geliştirme için temel oluşturur.",
      "KVKK uyumluluğu da bu modülün önceliklerinden biridir. Bağışçıların veri işleme onayları kayıt altında tutulur, silme talepleri panelden yönetilebilir. Hukuki gereklilikler yerine getirilirken operasyonel verimlilik de korunur.",
    ],
    faq: [
      { q: "Mevcut bağışçı verilerimi sisteme nasıl aktarırım?", a: "Excel veya CSV formatında hazırladığınız bağışçı listesini toplu olarak sisteme yükleyebilirsiniz. Aktarım sırasında veri eşleme aracı sizi yönlendirir." },
      { q: "Bağışçı verileri KVKK kapsamında saklanıyor mu?", a: "Evet. Veriler Türkiye'de barındırılan sunucularda saklanır. Açık rıza kayıtları tutulur, silme talepleri panelden yönetilebilir." },
      { q: "Pasif bağışçılara nasıl ulaşabilirim?", a: "Belirli süredir bağış yapmayan bağışçılar sistem tarafından pasif olarak işaretlenir. Bu gruba özel yeniden aktivasyon mesajı toplu olarak gönderilebilir." },
      { q: "Bağışçı segmentleri nasıl oluşturuluyor?", a: "Bağış tutarı, sıklık, ilgi alanı veya son bağış tarihi gibi kriterlere göre otomatik veya manuel segment tanımlanabilir." },
    ],
    relatedSlugs: ["duzenli-bagis", "whatsapp-bildirimleri", "raporlama"],
  },
  {
    slug: "kurban-organizasyonu",
    metaTitle: "Online Kurban Organizasyonu Dernek & Vakıf | Pekin Teknoloji",
    metaDesc: "Dernekler ve vakıflar için dijital kurban kampanyası yönetimi. Online kurban siparişi, hisse takibi, kesim bildirimi ve vekalet sistemi. Bayramda tam kontrol.",
    badge: "Kurban Modülü",
    icon: "🐑",
    accentColor: "#b45309",
    heroTitle: "Dijital Kurban Organizasyonu",
    heroDesc: "Kurban bayramı siparişlerini online alın, hisse takibini otomatikleştirin, kesim bildirimlerini bağışçılara iletin. Manuel tablolar yerine tek ekrandan tam kontrol.",
    plan: "Başlangıç",
    stats: [
      { num: "Online", label: "sipariş ve ödeme" },
      { num: "Otomatik", label: "kesim bildirimi" },
      { num: "Sıfır", label: "Manuel tablolama" },
    ],
    benefits: [
      { icon: "🛒", title: "Online Sipariş Alma", desc: "Bağışçılar büyükbaş veya küçükbaş kurban seçer, hisse sayısını belirler ve güvenli ödeme yapar." },
      { icon: "📊", title: "Hisse Takip Paneli", desc: "Her hayvan için kaç hisse doldu, kim aldı, ödeme durumu nedir anlık olarak görülür." },
      { icon: "📲", title: "Kesim Bildirimi", desc: "Kurban kesildiğinde bağışçıya otomatik SMS veya WhatsApp bildirimi gönderilir, vekalet tamamlanır." },
    ],
    features: [
      "Büyükbaş (7 hisse) ve küçükbaş (1 hisse) kurban tipleri ayrı ayrı tanımlanır",
      "Fiyat, kesim tarihi ve lokasyon her yil panelden guncellenir",
      "Bağışçı adına kurban vekalet belgesi otomatik olarak oluşturulur",
      "Hisse tamamlanan hayvanlar otomatik olarak sipariş akışından çıkarılır",
      "Kesim sonrası fotoğraf veya video bağışçıya gönderilebilir",
      "Uluslararası bağışçılar için döviz ile ödeme desteği",
    ],
    howItWorks: [
      { step: "01", title: "Kampanya Acilir", desc: "Kurban tiplerini, fiyatlarini ve kesim tarihini girerek kampanyanizi yayinlayin." },
      { step: "02", title: "Siparis Alinir", desc: "Bagiscilar online siparis verir, odeme yapar; vekalet belgesi aninda iletilir." },
      { step: "03", title: "Hisseler Takip Edilir", desc: "Doldurulan hisseler panelde anlık guncellenir, eksik hisseler otomatik bildirilir." },
      { step: "04", title: "Kesim Bildirimi", desc: "Kurban kesildiginde bagisciya otomatik bildirim gider, vekalet tamamlanir." },
    ],
    seoContent: [
      "Kurban organizasyonu pek cok dernek ve vakif icin en yogun donemdir. Online kurban kampanyasi yonetimi bu sureci kolaylastirir: bağışçılar istediği zaman sipariş verebilir, kurum ise hisse durumunu anlık izleyebilir.",
      "Geleneksel yöntemlerde kurban siparişleri telefon, WhatsApp veya formlarla alınır; tablolara manuel girilir. Bu süreç hataya açıktır ve yoğun dönemde ciddi iş gücü gerektirir. Dijital kurban modülü tüm bu adımları otomatikleştirir.",
      "SEO açısından kurban kampanyası sayfaları bayram öncesi dönemde yüksek arama hacmi oluşturur. Optimize edilmiş kampanya sayfaları organik trafikten bağış almak için kritik öneme sahiptir.",
    ],
    faq: [
      { q: "Kac kurban tipi tanimlanabilir?", a: "Buyukbas, kucukbas, hisse veya tam kurban gibi istediğiniz sayida kurban tipi panelden tanimlanabilir. Her tip icin ayri fiyat ve hisse sayisi belirtilir." },
      { q: "Vekalet belgesi otomatik olusturuluyor mu?", a: "Evet. Odeme tamamlandiginda bagisci adina dijital vekalet belgesi otomatik olusturulur ve e-posta ile iletilir." },
      { q: "Uluslararasi bagiscilardan odeme alinabiliyor mu?", a: "Evet. Dovizli odeme destegi ile yurt disindaki bagiscilar kendi para birimiyle siparis verebilir." },
      { q: "Kalan hisseler nasil yonetilir?", a: "Dolmayan hisseler icin sistem otomatik uyari verir. Isterseniz eksik hisseleri kendi kurumunuz tamamlayabilir ya da kampanyayi kapatabilirsiniz." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "dijital-makbuz", "bagisci-yonetimi"],
  },
  {
    slug: "su-kuyusu",
    metaTitle: "Su Kuyusu Kampanyası Yazılımı Dernek & Vakıf | Pekin Teknoloji",
    metaDesc: "Online su kuyusu bağış kampanyası yönetimi. Proje bazlı bağış toplama, ilerleme takibi, fotoğraf güncelleme ve bağışçı adına kuyu açma. STK proje modülü.",
    badge: "Proje Bazlı Bağış",
    icon: "💧",
    accentColor: "#0284c7",
    heroTitle: "Su Kuyusu ve Proje Bazlı Bağış",
    heroDesc: "Su kuyusu, okul yapımı, gıda paketi gibi proje bazlı bağış kampanyalarını kolayca yönetin. Hedef tutarı belirleyin, ilerlemeyi paylaşın, projeyi tamamlayın.",
    plan: "Başlangıç",
    stats: [
      { num: "Proje", label: "bazlı takip" },
      { num: "Otomatik", label: "ilerleme bildirimi" },
      { num: "Adına", label: "kuyu açma desteği" },
    ],
    benefits: [
      { icon: "🎯", title: "Proje Hedef Takibi", desc: "Her projenin hedef tutarı, toplanan miktar ve kalan tablo ile ilerleme çubuğu anlık güncellenir." },
      { icon: "📸", title: "Sahadan Fotoğraf Güncellemesi", desc: "Kuyu açılışı veya proje tamamlanma aşamalarında fotoğraf yükleyin; bağışçılara ve kamuoyuna paylaşın." },
      { icon: "🏷️", title: "Bağışçı Adına Proje", desc: "Bağışçı tam bedeli karşıladığında veya anlamlı miktarda bağış yaptığında proje kuyuya onun adı verilebilir." },
    ],
    features: [
      "Su kuyusu, okul, ambulans, gıda paketi gibi farklı proje tipleri tanımlanabilir",
      "Proje sayfasında hedef tutar, toplanan miktar ve bağışçı listesi gösterilir",
      "Tek bağışçıyla tamamlanan projeler adına kuyu açma seçeneği sunar",
      "Proje tamamlanınca bağışçılara otomatik bildirim ve teşekkür gönderilir",
      "Sahadan fotoğraf ve güncelleme eklemek için mobil uyumlu yönetim paneli",
      "Proje bazında gelir-gider takibi ve şeffaflık raporu oluşturulabilir",
    ],
    howItWorks: [
      { step: "01", title: "Proje Olusturun", desc: "Proje adini, hedef tutarini, aciklamasini ve gorselini girerek kampanya sayfasini yayinlayin." },
      { step: "02", title: "Bagislar Toplanir", desc: "Bagiscilar proje sayfasindan tek seferlik veya duzenli bagis yapar; ilerleme sayaci guncellenir." },
      { step: "03", title: "Sahadan Guncelleme", desc: "Proje tamamlama asamalarinda fotograf ve video yukleyin; bagiscilar ilerlemeleri gorebilir." },
      { step: "04", title: "Proje Tamamlandi", desc: "Hedef tutara ulasilinca bagiscilara otomatik bildirim gider, tesekkur mesaji iletilir." },
    ],
    seoContent: [
      "Su kuyusu kampanyaları Türkiye'deki insani yardım derneklerinin en sık yürüttüğü proje türlerinden biridir. Online platform aracılığıyla yürütülen proje bazlı bağış kampanyaları, hem daha geniş bir bağışçı kitlesine ulaşmayı hem de şeffaf ilerleme raporlaması yapmayı mümkün kılar.",
      "Pekin Teknoloji su kuyusu modülü proje sayfası oluşturmayı son derece kolaylaştırır. Hedef tutar, proje görseli ve açıklaması girildikten sonra kampanya sayfası dakikalar içinde yayına alınabilir. Bağış toplandıkça ilerleme çubuğu otomatik güncellenir, bağışçılar motivasyonlarını kaybetmez.",
      "Bağışçı adına kuyu açma özelliği, özellikle vefat edenler adına yapılan hayır bağışlarında tercih edilmektedir. Bu kişiselleştirme unsuru hem bağışçı bağlılığını artırır hem de kurumunuza olan güveni pekiştirir.",
    ],
    faq: [
      { q: "Kac farkli proje tipi tanimlanabilir?", a: "Su kuyusu, okul, gida paketi, ambulans gibi istediginiz sayida proje tipi olusturabilirsiniz. Her tip icin ayri gorsel ve aciklama girilebilir." },
      { q: "Bagisci adina kuyu nasil aciliyor?", a: "Tam proje bedelini karsilayan bagisci veya tercih edilen bir esik degeri asildiginda projeye bagisci adi eklenebilir. Bu islem admin panelinden onaylanir." },
      { q: "Proje tamamlaninca ne oluyor?", a: "Proje otomatik olarak kapanir, bagiscilara tesekkur bildirimi gider. Sahadan fotograf ve video yukleyerek projenin tamamlandigini paylasilabilir." },
      { q: "Birden fazla aktif proje olabilir mi?", a: "Evet. Ayni anda su kuyusu, okul, gida paketi gibi birden fazla proje kampanyasi ayni anda aktif olabilir; her biri ayri sayfada takip edilir." },
    ],
    relatedSlugs: ["bagis-kampanyasi", "bagisci-yonetimi", "raporlama"],
  },
];
